---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-stocks-live
  namespace: demo-stocks-live
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: stocks
  serviceName: demo
  template:
    metadata:
      labels:
        demo: stocks
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: twelve-data-token
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi


